import { createFileRoute, Link } from "@tanstack/react-router";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — LaunchPad EIC" },
      {
        name: "description",
        content:
          "What LaunchPad EIC collects, how your posts and AI Coach chats are stored, who can see them, and how to delete your account and data.",
      },
      { property: "og:title", content: "Privacy Policy — LaunchPad EIC" },
      {
        property: "og:description",
        content:
          "What LaunchPad EIC collects, how it is stored and used, and how to delete your data.",
      },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: PrivacyPage,
});

const UPDATED = "August 18, 2026";

function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-2xl px-4 py-10 pb-24">
        <Link to="/" className="text-sm text-primary hover:underline">
          ← Back to LaunchPad EIC
        </Link>
        <h1 className="mt-4 text-3xl font-bold tracking-tight">Privacy Policy</h1>
        <p className="mt-1 text-sm text-muted-foreground">Last updated: {UPDATED}</p>

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-foreground/90">
          <section className="space-y-2">
            <h2 className="text-lg font-semibold">The short version</h2>
            <p>
              We collect what we need to run the app: your account details, the profile info you
              give us, what you post, your roadmap progress, and your AI Coach conversations.{" "}
              <strong>We do not sell your data.</strong> You can delete your account and everything
              tied to it at any time from Profile → Settings.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">What we collect</h2>
            <p className="font-medium">Account information</p>
            <p>
              Your email address and password (stored hashed by our authentication provider), or —
              if you sign in with Google — your Google account email and basic profile details that
              Google shares with us. We never see your Google password.
            </p>
            <p className="font-medium">Profile information you enter</p>
            <p>
              Name, current role, industry, years of experience, career goal, optional LinkedIn URL,
              and an optional profile photo.
            </p>
            <p className="font-medium">Things you create in the app</p>
            <p>
              Posts and their topic tags, comments, likes, reposts, who you follow, notifications
              generated by that activity, your career milestones and tasks, weekly action steps, and
              your XP, level, and streak history.
            </p>
            <p className="font-medium">AI Coach conversations</p>
            <p>
              Your messages to the AI Coach and its replies are stored in your account so your chat
              history is there when you come back. You can clear your chat history from the Coach
              screen at any time.
            </p>
            <p className="font-medium">Subscription information</p>
            <p>
              If paid features are enabled, we store your subscription status, plan, and renewal
              date. Card details are handled by the payment processor — we never see or store your
              card number.
            </p>
            <p className="font-medium">What we don't collect</p>
            <p>
              We do not run third-party advertising or analytics trackers in the app today. We do not
              collect your location, contacts, or browsing activity on other sites. Our hosting
              provider keeps standard server logs (things like IP address, timestamp, and which page
              was requested) for security and reliability.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">How your data is stored</h2>
            <p>
              Your data lives in a managed cloud database and file storage, encrypted in transit
              (HTTPS) and encrypted at rest by the hosting provider. Access is restricted per
              account with database-level rules, so other users can only see what the app is meant
              to show them. Profile photos are stored in a private bucket and served through
              short-lived signed links.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Who can see what</h2>
            <ul className="list-disc space-y-1 pl-5">
              <li>
                <strong>Visible to other signed-in users:</strong> your profile (name, role,
                industry, photo, LinkedIn if you add one), your posts, comments, likes, reposts, and
                follows.
              </li>
              <li>
                <strong>Private to you:</strong> your AI Coach conversations, your milestones,
                tasks, weekly action steps, XP history, notifications, and subscription status.
              </li>
              <li>
                <strong>Never public:</strong> your email address and password.
              </li>
            </ul>
            <p>
              Anything you post to the feed can be seen, screenshotted, or shared by other users.
              Don't post confidential or sensitive information.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">How we use your data</h2>
            <ul className="list-disc space-y-1 pl-5">
              <li>To run your account, the feed, notifications, and your roadmap.</li>
              <li>
                To personalize the AI Coach and roadmap generator using your profile and roadmap
                context.
              </li>
              <li>To keep the app secure and prevent abuse.</li>
              <li>To support you when you contact us.</li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Service providers we share data with</h2>
            <p>
              We don't sell your data and we don't share it with advertisers. We do rely on a small
              number of providers to run the app, and they only process data on our behalf:
            </p>
            <ul className="list-disc space-y-1 pl-5">
              <li>
                <strong>Hosting, database, authentication, and file storage</strong> — stores your
                account and app data.
              </li>
              <li>
                <strong>AI model provider</strong> — when you use the AI Coach or generate a
                roadmap, your message plus relevant profile and roadmap context is sent to a
                third-party AI model (currently Google's Gemini, accessed through our hosting
                platform's AI gateway) to produce the response.
              </li>
              <li>
                <strong>Payment processor</strong> — handles card details directly if you subscribe.
              </li>
              <li>
                <strong>YouTube</strong> — the Conversations tab loads our public YouTube channel
                feed and embeds videos; YouTube may set its own cookies when you play one.
              </li>
            </ul>
            <p>We may also disclose data if legally required to do so.</p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">How long we keep it</h2>
            <p>
              We keep your data while your account is active. Delete your account and we delete your
              account record and the data attached to it — profile, posts, comments, likes, reposts,
              follows, notifications, milestones, tasks, action steps, XP history, and AI Coach
              conversations. Backups and server logs may retain copies for a short period before
              rolling off.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Your choices</h2>
            <ul className="list-disc space-y-1 pl-5">
              <li>Edit your profile any time from the Profile tab.</li>
              <li>Edit or delete your own posts and comments.</li>
              <li>Clear your AI Coach history with the "Clear" button on the Coach screen.</li>
              <li>
                Delete your entire account and data from <strong>Profile → Settings → Delete
                account</strong>.
              </li>
              <li>
                Request a copy of your data, or ask us to correct or delete something, by emailing
                us.
              </li>
            </ul>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Age</h2>
            <p>
              LaunchPad EIC is for people who are at least 16. We don't knowingly collect data from
              children. If you believe a child has created an account, email us and we'll remove it.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Changes</h2>
            <p>
              If we change what we collect or how we use it, we'll update this page and the date at
              the top, and tell you in the app when the change is significant.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Contact</h2>
            <p>
              Privacy questions or requests:{" "}
              <a className="text-primary hover:underline" href="mailto:privacy@launchpadeic.com">
                privacy@launchpadeic.com
              </a>
              . We aim to respond within 30 days.
            </p>
            <p className="text-muted-foreground">
              See also our{" "}
              <Link to="/terms" className="text-primary hover:underline">
                Terms of Service
              </Link>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
