import { createFileRoute, Link } from "@tanstack/react-router";
import { LEGAL_VERSION, LEGAL_VERSION_LABEL } from "@/lib/legal";

export const Route = createFileRoute("/privacy")({
  head: () => ({
    meta: [
      { title: "Privacy Policy — LaunchPad EIC" },
      {
        name: "description",
        content:
          "What LaunchPad EIC collects, how your posts and AI Coach chats are stored, who can see them, your rights, and how to export or delete everything.",
      },
      { property: "og:title", content: "Privacy Policy — LaunchPad EIC" },
      {
        property: "og:description",
        content:
          "What LaunchPad EIC collects, how it is stored and used, your rights, and how to export or delete your data.",
      },
      { property: "og:type", content: "article" },
      { name: "twitter:card", content: "summary" },
    ],
  }),
  component: PrivacyPage,
});

// TODO before this is the published policy: replace ENTITY and ENTITY_ADDRESS
// with the registered legal entity. A privacy policy that does not identify the
// controller is incomplete under every US state privacy law, and a university
// cannot contract with a product name.
const ENTITY = "Marina Samuel, a sole proprietor doing business as LaunchPad EIC";
const ENTITY_ADDRESS = "[MAILING ADDRESS]";
const DATA_REGION = "[REGION]";

function PrivacyPage() {
  return (
    <div className="min-h-screen bg-background">
      <div className="mx-auto max-w-2xl px-4 py-10 pb-24">
        <Link to="/" className="text-sm text-primary hover:underline">
          ← Back to LaunchPad EIC
        </Link>
        <h1 className="mt-4 text-3xl font-bold tracking-tight">Privacy Policy</h1>
        <p className="mt-1 text-sm text-muted-foreground">
          Version {LEGAL_VERSION} · Last updated: {LEGAL_VERSION_LABEL}
        </p>

        <div className="mt-8 space-y-8 text-sm leading-relaxed text-foreground/90">
          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Who we are</h2>
            <p>
              LaunchPad EIC is operated by <strong>{ENTITY}</strong>, at {ENTITY_ADDRESS}. We are
              the data controller for the personal data described here. Contact us at{" "}
              <a className="text-primary hover:underline" href="mailto:privacy@launchpadeic.com">
                privacy@launchpadeic.com
              </a>
              .
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">The short version</h2>
            <p>
              We collect what we need to run the app: your account details, the profile info you
              give us, what you post, your roadmap progress, and your AI Coach conversations.{" "}
              <strong>
                We do not sell your data, we do not share it for advertising, and we do not use it
                to train AI models.
              </strong>{" "}
              You can download everything we hold about you, and delete your account and everything
              tied to it, at any time from Profile → Settings.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">What we collect</h2>
            <p className="font-medium">Account information</p>
            <p>
              Your email address and password (stored hashed by our authentication provider), or —
              if you sign in with Google — your Google account email and basic profile details that
              Google shares with us. We never see your Google password.
            </p>
            <p className="font-medium">Profile information you enter</p>
            <p>
              Name, current role, industry, years of experience, career goal, optional LinkedIn URL,
              and an optional profile photo.
            </p>
            <p className="font-medium">Things you create in the app</p>
            <p>
              Posts and their topic tags, comments, likes, reposts, who you follow, notifications
              generated by that activity, your career milestones and tasks, weekly action steps, and
              your XP, level, and streak history.
            </p>
            <p className="font-medium">AI Coach conversations</p>
            <p>
              Your messages to the AI Coach and its replies are stored in your account so your chat
              history is there when you come back. You can clear your chat history from the Coach
              screen at any time.
            </p>
            <p className="font-medium">Consent records</p>
            <p>
              When you create an account we record which version of our Terms and this Privacy
              Policy you accepted, and when, so both of us have a record of what was agreed.
            </p>
            <p className="font-medium">Subscription information</p>
            <p>
              If paid features are enabled, we store your subscription status, plan, and renewal
              date. Card details are handled by the payment processor — we never see or store your
              card number.
            </p>
            <p className="font-medium">Safety records</p>
            <p>
              If you report content or block another user, we store that report or block, including
              what you tell us, so we can act on it and recognise a pattern if someone is reported
              repeatedly.
            </p>
            <p className="font-medium">What we don't collect</p>
            <p>
              We do not run third-party advertising or analytics trackers in the app today. We do
              not collect your location, contacts, or browsing activity on other sites. We do not
              ask for and do not want health information, government ID numbers, or financial
              account numbers. Our hosting provider keeps standard server logs (things like IP
              address, timestamp, and which page was requested) for security and reliability.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">How we use it</h2>
            <ul className="list-disc space-y-1 pl-5">
              <li>To run your account, the feed, notifications, your roadmap, and your subscription.</li>
              <li>
                To personalise the AI Coach and roadmap generator using your profile and roadmap
                context.
              </li>
              <li>To keep the app safe, prevent abuse, and act on reports.</li>
              <li>To support you when you contact us.</li>
              <li>To meet legal obligations and respond to valid legal process.</li>
            </ul>
            <p>
              <strong>We do not use your data to train AI models</strong>, and our AI provider is
              contractually prohibited from using it to train theirs.
            </p>
            <p className="font-medium">Automated processing</p>
            <p>
              The AI Coach and the roadmap generator produce suggestions from your profile and
              roadmap. These are suggestions only. Nothing in LaunchPad EIC makes an automated
              decision with a legal or similarly significant effect on you — we do not screen,
              score, rank, or filter you for any employer, school, or third party, and we will not
              without telling you first and asking.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Who can see what</h2>
            <ul className="list-disc space-y-1 pl-5">
              <li>
                <strong>Visible to other signed-in users:</strong> your profile (name, role,
                industry, years of experience, photo, LinkedIn if you add one), your posts,
                comments, likes, reposts, and follows.
              </li>
              <li>
                <strong>Private to you:</strong> your AI Coach conversations, milestones, tasks,
                weekly action steps, XP history, notifications, consent records, and subscription
                status.
              </li>
              <li>
                <strong>Never visible to other users:</strong> your email address and your password.
              </li>
            </ul>
            <p>
              These boundaries are enforced in the database itself with row-level security policies,
              not only in the app's interface.
            </p>
            <p>
              Anything you post to the feed can be seen, screenshotted, or shared by other users.
              Don't post confidential information — yours, your employer's, or anyone else's.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Where it lives and how it's protected</h2>
            <p>
              Your data is held in a managed cloud database and file storage in {DATA_REGION}. It is
              encrypted in transit (TLS) and encrypted at rest by the hosting provider. Access is
              restricted per account by database-level row security policies. Profile photos are
              stored in a private bucket and served through short-lived signed links.
              Administrative access is limited to named individuals, and privileged actions are
              logged to an append-only record.
            </p>
            <p>
              No system is perfectly secure and we won't claim otherwise. If a breach affects your
              personal data we will notify you and the relevant authorities as required by law,
              without undue delay.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Service providers</h2>
            <p>
              We don't sell your data and we don't share it with advertisers. We rely on a small
              number of providers to run the app, and they only process data on our behalf:
            </p>
            <ul className="list-disc space-y-1 pl-5">
              <li>
                <strong>Hosting, database, authentication, and file storage</strong> — stores your
                account and app data.
              </li>
              <li>
                <strong>AI model provider</strong> — when you use the AI Coach or generate a
                roadmap, your message plus relevant profile and roadmap context is sent to a
                third-party AI model (currently Google's Gemini, accessed through our hosting
                platform's AI gateway) to produce the response. It is not used to train that model.
              </li>
              <li>
                <strong>Payment processor</strong> — handles card details directly if you subscribe.
              </li>
              <li>
                <strong>YouTube</strong> — the Watch tab loads our public YouTube channel feed and
                embeds videos; YouTube may set its own cookies when you play one.
              </li>
            </ul>
            <p>
              We may also disclose data where legally required — a subpoena, court order, or other
              valid legal process — or where necessary to protect someone's safety. We will tell you
              when we are permitted to.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">How long we keep it</h2>
            <ul className="list-disc space-y-1 pl-5">
              <li>Account, profile, posts, and activity — while your account is active.</li>
              <li>AI Coach conversations — until you clear them, or you delete your account.</li>
              <li>Consent records — account lifetime plus 3 years, as proof of what was agreed.</li>
              <li>Safety reports and blocks — 2 years after resolution.</li>
              <li>Server logs — 30 days. Backups — 30 days on a rolling basis.</li>
            </ul>
            <p>
              Delete your account and we delete your account record and the data attached to it —
              profile, posts, comments, likes, reposts, follows, notifications, milestones, tasks,
              action steps, XP history, and AI Coach conversations. This is enforced by cascading
              deletion in the database, not by a manual process.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Your rights</h2>
            <ul className="list-disc space-y-1 pl-5">
              <li>
                <strong>Access and take your data elsewhere</strong> — download everything we hold
                about you as a JSON file from <strong>Profile → Settings → Download my data</strong>.
                No request needed.
              </li>
              <li>
                <strong>Correct</strong> — edit your profile any time; edit or delete your own posts
                and comments.
              </li>
              <li>
                <strong>Delete</strong> — <strong>Profile → Settings → Delete account</strong>.
                Immediate and permanent.
              </li>
              <li>
                <strong>Clear your AI Coach history</strong> — the "Clear" button on the Coach
                screen.
              </li>
              <li>
                <strong>Object or restrict</strong> — email us and tell us what you object to.
              </li>
              <li>
                <strong>Opt out</strong> — we do not sell personal data, do not process it for
                targeted advertising, and do not profile you for decisions with legal or similarly
                significant effects. If that ever changes we will honour universal opt-out signals
                including Global Privacy Control, and tell you before the change takes effect.
              </li>
            </ul>
            <p>
              If you are in New Jersey, the New Jersey Data Privacy Act gives you these rights.
              Residents of California, Colorado, Connecticut, Virginia and other states with
              comprehensive privacy laws have substantially similar rights, and we apply the same
              process to everyone.
            </p>
            <p className="font-medium">How to make a request</p>
            <p>
              Email{" "}
              <a className="text-primary hover:underline" href="mailto:privacy@launchpadeic.com">
                privacy@launchpadeic.com
              </a>{" "}
              from the address on your account. We will respond within 45 days, and may extend once
              by a further 45 days where the request is complex, telling you why. We will not charge
              you and will not treat you differently for asking.
            </p>
            <p className="font-medium">If we refuse — your right to appeal</p>
            <p>
              If we decline a request we will tell you why in writing and explain how to appeal. To
              appeal, reply to our decision with "Appeal" in the subject line. A different person
              will review it and respond within 45 days with a written explanation. If we deny the
              appeal we will give you a link to submit a complaint to the New Jersey Division of
              Consumer Affairs, or to your own state's Attorney General.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Age</h2>
            <p>
              LaunchPad EIC is for people who are at least 16, and is designed for adults in the
              early years of their careers. We don't knowingly collect data from children under 13,
              and we do not sell personal data or use it for targeted advertising for anyone under
              17. If you believe a child has created an account, email us and we'll remove it.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Accessibility</h2>
            <p>
              We are working toward conformance with WCAG 2.1 Level AA. See our{" "}
              <Link to="/accessibility" className="text-primary hover:underline">
                Accessibility Statement
              </Link>
              . If any part of this app is a barrier for you, email{" "}
              <a
                className="text-primary hover:underline"
                href="mailto:accessibility@launchpadeic.com"
              >
                accessibility@launchpadeic.com
              </a>{" "}
              and we will fix it or give you the information another way.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Institutional users</h2>
            <p>
              If you are using LaunchPad EIC through your university or employer, that institution
              may have a separate agreement with us governing how we handle data about you. Where
              that agreement is stricter than this policy, it wins. Your institution does not have
              access to your AI Coach conversations or your private roadmap unless we have told you
              otherwise in advance and in plain terms.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Changes</h2>
            <p>
              If we change what we collect or how we use it, we'll update this page and the version
              at the top, and tell you in the app when the change is significant. We will not apply
              a materially different use to data we already hold without asking you first.
            </p>
          </section>

          <section className="space-y-2">
            <h2 className="text-lg font-semibold">Contact</h2>
            <p>
              Privacy questions, requests, or appeals:{" "}
              <a className="text-primary hover:underline" href="mailto:privacy@launchpadeic.com">
                privacy@launchpadeic.com
              </a>
              . Accessibility:{" "}
              <a
                className="text-primary hover:underline"
                href="mailto:accessibility@launchpadeic.com"
              >
                accessibility@launchpadeic.com
              </a>
              . Postal: {ENTITY}, {ENTITY_ADDRESS}.
            </p>
            <p className="text-muted-foreground">
              See also our{" "}
              <Link to="/terms" className="text-primary hover:underline">
                Terms of Service
              </Link>
              .
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
