/**
 * Types for the Actions of the Week tables.
 *
 * `types.ts` in this folder is regenerated by Lovable from the live database.
 * Since these tables were added by hand (via GitHub, not the Lovable agent),
 * they aren't in that generated file yet. This module layers them on top so
 * the new code stays fully type-checked without touching the generated file.
 *
 * Once Lovable regenerates types.ts and these tables appear there, you can
 * swap `sbw` back to the plain `supabase` client and delete this file.
 */
import type { SupabaseClient } from "@supabase/supabase-js";
import { supabase } from "./client";

export type Difficulty = "easy" | "medium" | "stretch";

export type WeeklyTheme = {
  id: string;
  title: string;
  subtitle: string | null;
  episode_number: number | null;
  episode_url: string | null;
  guest_name: string | null;
  summary: string;
  key_advice: string[];
  accent_color: string | null;
  is_active: boolean;
  published_at: string | null;
  created_at: string;
};

export type WeeklyAction = {
  id: string;
  theme_id: string;
  title: string;
  description: string | null;
  difficulty: Difficulty;
  xp_reward: number;
  sort_order: number;
};

export type UserActionCompletion = {
  id: string;
  user_id: string;
  action_id: string;
  completed_at: string;
  reflection: string | null;
};

export type WeeklyDatabase = {
  public: {
    Tables: {
      weekly_themes: {
        Row: WeeklyTheme;
        Insert: Partial<WeeklyTheme> & { title: string };
        Update: Partial<WeeklyTheme>;
        Relationships: [];
      };
      weekly_actions: {
        Row: WeeklyAction;
        Insert: Partial<WeeklyAction> & { theme_id: string; title: string };
        Update: Partial<WeeklyAction>;
        Relationships: [];
      };
      user_action_completions: {
        Row: UserActionCompletion;
        Insert: Partial<UserActionCompletion> & { user_id: string; action_id: string };
        Update: Partial<UserActionCompletion>;
        Relationships: [];
      };
      user_roles: {
        Row: { id: string; user_id: string; role: string; created_at: string };
        Insert: { user_id: string; role?: string };
        Update: { role?: string };
        Relationships: [];
      };
    };
    Views: Record<string, never>;
    Functions: {
      publish_theme: {
        Args: { p_theme_id: string };
        Returns: undefined;
      };
      action_completion_counts: {
        Args: { p_theme_id: string };
        Returns: { action_id: string; completions: number }[];
      };
      admin_theme_stats: {
        Args: Record<string, never>;
        Returns: { theme_id: string; completions: number; participants: number }[];
      };
      has_role: {
        Args: { _user_id: string; _role: string };
        Returns: boolean;
      };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

/** The shared Supabase client, typed for the Actions of the Week tables. */
export const sbw = supabase as unknown as SupabaseClient<WeeklyDatabase>;

export const DIFFICULTY_LABEL: Record<Difficulty, string> = {
  easy: "Quick win",
  medium: "Takes effort",
  stretch: "Stretch",
};

export const DIFFICULTY_CLASS: Record<Difficulty, string> = {
  easy: "bg-emerald-500/12 text-emerald-600 dark:text-emerald-400",
  medium: "bg-primary/12 text-primary",
  stretch: "bg-amber-500/15 text-amber-600 dark:text-amber-400",
};
